{% set name = "dlib" %}
{% set version = "19.20.0" %}
{% set tag = "v" ~ ".".join(version.split(".")[:2]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3f5070df590c3f510dde2f4c84b1b20e3ef64a02932ed657da490834ecac7e4

  patches:
    - lapack_sgetrf.patch      # [unix]
    - cxx11_detection.patch
    - setup_cmake_args.patch

build:
  skip: true  # [win and py<35]
  number: 2
  run_exports:
    - {{ pin_subpackage('dlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - jpeg
    - libcblas  # [not win]
    - liblapack   # [not win]
    - libpng
    - numpy
    - pip
    - pybind11
    - python
    - sqlite  # [not win]
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml
  source_files:
    - tools/python/test
  requires:
    - more-itertools
    - pillow
    - pip
    - pytest
    - pytest-azurepipelines
    - tqdm

  imports:
    - dlib

  commands:
    - python -m pip check
    - cd tools/python/test
    # setup.cfg configures test options
    - copy {{ RECIPE_DIR }}/setup.cfg .  # [win]
    - cp {{ RECIPE_DIR }}\setup.cfg .  # [not win]
    - python -m pytest

about:
  home: http://dlib.net/
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: toolkit for making real world machine learning and data analysis applications
  dev_url: https://github.com/davisking/dlib
  doc_source_url: https://github.com/davisking/dlib/tree/{{ tag }}/docs
  description: |-
    Dlib is a modern C++ toolkit containing machine learning algorithms and tools
    for creating complex software in C++ to solve real world problems. See
    http://dlib.net for the main project documentation and API reference.

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
